name: Build and deploy site

on:
  push:
    branches: 
      - Master
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Hugo CLI
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.1'
          extended: true
 
      - name: Build site with Hugo cli
        run: hugo -t greentech
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.CI_DEPLOY_TO_REPO }}
          publish_dir: ./public
          external_repository: greentechdev/greentechdev.github.io
          publish_branch: master # The branch the action should deploy to.
